apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : reloader
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: reloader
  source:
    path   : "deployments/kubernetes/chart/reloader"
    repoURL: "https://github.com/stakater/Reloader.git"
    targetRevision: HEAD
    helm:
      releaseName: reloader
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
